### ISSUE TITLE
Errors building documentation locally

### ISSUE THREAD

**Issue by MarkRivers** [tomography/tomoscan#9]
When I try to build the documentation locally I get the following errors:
```
corvette:~/devel/tomoscan/docs>make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v3.0.2
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 4 source files that are out of date
updating environment: 0 added, 6 changed, 0 removed
reading sources... [100%] source/usage
WARNING: autodoc: failed to import module 'tomoscan_13bm' from module 'tomoscan'; the following exception was raised:
Traceback (most recent call last):
  File "/home/epics/anaconda3/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/home/epics/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/epics/devel/tomoscan/tomoscan/tomoscan_13bm.py", line 6, in <module>
    class tomoscan_13bm(tomoscan):
TypeError: module() takes at most 2 arguments (3 given)

looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/epics/devel/tomoscan/docs/source/credits.rst: WARNING: Citation [AD:01] is not referenced.
/home/epics/devel/tomoscan/docs/source/credits.rst: WARNING: Citation [AD:02] is not referenced.
done
preparing documents... done
writing output... [100%] source/usage
generating indices...  genindex py-modindexdone
highlighting module code... [100%] tomoscan.tomoscan
writing additional pages...  searchdone
copying images... [100%] source/img/TomoCollectConfigInfo.png
copying downloadable files... [100%] demo/13bm/TomoCollect.substitutions
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 3 warnings.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.
```

@decarlof any idea how to get rid of these errors?

I have a related question.  When git pushes are done does the documentation automatically get build on readthedocs, i.e. is there a Travis job to do that, or are you doing it manually?

**Comment by decarlof** [comment]
this is fixed. On the doc build: by setting  a webhook on readthedocs, commits on github will trigger new builds. At the moment the webhook is not set as I am doing the builds off my readthedoc account. I can set it if we decide to keep it there.
